// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: empresa.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empresa struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// UUID id = 1;
	// string id =1;
	Nome      string `protobuf:"bytes,2,opt,name=nome,proto3" json:"nome,omitempty"`
	Atividade string `protobuf:"bytes,3,opt,name=atividade,proto3" json:"atividade,omitempty"`
	Sede      string `protobuf:"bytes,4,opt,name=sede,proto3" json:"sede,omitempty"`
	Emissoes  string `protobuf:"bytes,5,opt,name=emissoes,proto3" json:"emissoes,omitempty"`
}

func (x *Empresa) Reset() {
	*x = Empresa{}
	if protoimpl.UnsafeEnabled {
		mi := &file_empresa_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empresa) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empresa) ProtoMessage() {}

func (x *Empresa) ProtoReflect() protoreflect.Message {
	mi := &file_empresa_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empresa.ProtoReflect.Descriptor instead.
func (*Empresa) Descriptor() ([]byte, []int) {
	return file_empresa_proto_rawDescGZIP(), []int{0}
}

func (x *Empresa) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *Empresa) GetAtividade() string {
	if x != nil {
		return x.Atividade
	}
	return ""
}

func (x *Empresa) GetSede() string {
	if x != nil {
		return x.Sede
	}
	return ""
}

func (x *Empresa) GetEmissoes() string {
	if x != nil {
		return x.Emissoes
	}
	return ""
}

type ListEmpresas struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Empresas []*Empresa `protobuf:"bytes,1,rep,name=empresas,proto3" json:"empresas,omitempty"`
}

func (x *ListEmpresas) Reset() {
	*x = ListEmpresas{}
	if protoimpl.UnsafeEnabled {
		mi := &file_empresa_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListEmpresas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEmpresas) ProtoMessage() {}

func (x *ListEmpresas) ProtoReflect() protoreflect.Message {
	mi := &file_empresa_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEmpresas.ProtoReflect.Descriptor instead.
func (*ListEmpresas) Descriptor() ([]byte, []int) {
	return file_empresa_proto_rawDescGZIP(), []int{1}
}

func (x *ListEmpresas) GetEmpresas() []*Empresa {
	if x != nil {
		return x.Empresas
	}
	return nil
}

type ParamId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ParamId) Reset() {
	*x = ParamId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_empresa_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParamId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamId) ProtoMessage() {}

func (x *ParamId) ProtoReflect() protoreflect.Message {
	mi := &file_empresa_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamId.ProtoReflect.Descriptor instead.
func (*ParamId) Descriptor() ([]byte, []int) {
	return file_empresa_proto_rawDescGZIP(), []int{2}
}

func (x *ParamId) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ParamNome struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nome string `protobuf:"bytes,1,opt,name=nome,proto3" json:"nome,omitempty"`
}

func (x *ParamNome) Reset() {
	*x = ParamNome{}
	if protoimpl.UnsafeEnabled {
		mi := &file_empresa_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParamNome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamNome) ProtoMessage() {}

func (x *ParamNome) ProtoReflect() protoreflect.Message {
	mi := &file_empresa_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamNome.ProtoReflect.Descriptor instead.
func (*ParamNome) Descriptor() ([]byte, []int) {
	return file_empresa_proto_rawDescGZIP(), []int{3}
}

func (x *ParamNome) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

type ParamEmissoes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Emissoes string `protobuf:"bytes,1,opt,name=emissoes,proto3" json:"emissoes,omitempty"`
}

func (x *ParamEmissoes) Reset() {
	*x = ParamEmissoes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_empresa_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParamEmissoes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamEmissoes) ProtoMessage() {}

func (x *ParamEmissoes) ProtoReflect() protoreflect.Message {
	mi := &file_empresa_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamEmissoes.ProtoReflect.Descriptor instead.
func (*ParamEmissoes) Descriptor() ([]byte, []int) {
	return file_empresa_proto_rawDescGZIP(), []int{4}
}

func (x *ParamEmissoes) GetEmissoes() string {
	if x != nil {
		return x.Emissoes
	}
	return ""
}

type UpdateEmissoesParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Emissoes string `protobuf:"bytes,2,opt,name=emissoes,proto3" json:"emissoes,omitempty"`
}

func (x *UpdateEmissoesParam) Reset() {
	*x = UpdateEmissoesParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_empresa_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateEmissoesParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEmissoesParam) ProtoMessage() {}

func (x *UpdateEmissoesParam) ProtoReflect() protoreflect.Message {
	mi := &file_empresa_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEmissoesParam.ProtoReflect.Descriptor instead.
func (*UpdateEmissoesParam) Descriptor() ([]byte, []int) {
	return file_empresa_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateEmissoesParam) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateEmissoesParam) GetEmissoes() string {
	if x != nil {
		return x.Emissoes
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_empresa_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_empresa_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_empresa_proto_rawDescGZIP(), []int{6}
}

var File_empresa_proto protoreflect.FileDescriptor

var file_empresa_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x65, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0f, 0x74, 0x77, 0x69, 0x72, 0x70, 0x2e, 0x64, 0x65, 0x73, 0x61, 0x66, 0x69, 0x6f, 0x47, 0x6f,
	0x22, 0x6b, 0x0a, 0x07, 0x45, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x6f, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x6d, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x61, 0x74, 0x69, 0x76, 0x69, 0x64, 0x61, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x61, 0x74, 0x69, 0x76, 0x69, 0x64, 0x61, 0x64, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x65, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x65, 0x64,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6d, 0x69, 0x73, 0x73, 0x6f, 0x65, 0x73, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6d, 0x69, 0x73, 0x73, 0x6f, 0x65, 0x73, 0x22, 0x44, 0x0a,
	0x0c, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x61, 0x73, 0x12, 0x34, 0x0a,
	0x08, 0x65, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x61, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x74, 0x77, 0x69, 0x72, 0x70, 0x2e, 0x64, 0x65, 0x73, 0x61, 0x66, 0x69, 0x6f, 0x47,
	0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x61, 0x52, 0x08, 0x65, 0x6d, 0x70, 0x72, 0x65,
	0x73, 0x61, 0x73, 0x22, 0x19, 0x0a, 0x07, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x49, 0x64, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x1f,
	0x0a, 0x09, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x4e, 0x6f, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x6f, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x6d, 0x65, 0x22,
	0x2b, 0x0a, 0x0d, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x45, 0x6d, 0x69, 0x73, 0x73, 0x6f, 0x65, 0x73,
	0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6d, 0x69, 0x73, 0x73, 0x6f, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x65, 0x6d, 0x69, 0x73, 0x73, 0x6f, 0x65, 0x73, 0x22, 0x41, 0x0a, 0x13,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x6d, 0x69, 0x73, 0x73, 0x6f, 0x65, 0x73, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6d, 0x69, 0x73, 0x73, 0x6f, 0x65, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6d, 0x69, 0x73, 0x73, 0x6f, 0x65, 0x73, 0x22,
	0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x32, 0xbe, 0x03, 0x0a, 0x0e, 0x45, 0x6d, 0x70,
	0x72, 0x65, 0x73, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x40, 0x0a, 0x0a, 0x41,
	0x64, 0x64, 0x45, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x61, 0x12, 0x18, 0x2e, 0x74, 0x77, 0x69, 0x72,
	0x70, 0x2e, 0x64, 0x65, 0x73, 0x61, 0x66, 0x69, 0x6f, 0x47, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x72,
	0x65, 0x73, 0x61, 0x1a, 0x18, 0x2e, 0x74, 0x77, 0x69, 0x72, 0x70, 0x2e, 0x64, 0x65, 0x73, 0x61,
	0x66, 0x69, 0x6f, 0x47, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x61, 0x12, 0x50, 0x0a,
	0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x6d, 0x69, 0x73, 0x73, 0x6f, 0x65, 0x73, 0x12,
	0x24, 0x2e, 0x74, 0x77, 0x69, 0x72, 0x70, 0x2e, 0x64, 0x65, 0x73, 0x61, 0x66, 0x69, 0x6f, 0x47,
	0x6f, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x6d, 0x69, 0x73, 0x73, 0x6f, 0x65, 0x73,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x1a, 0x18, 0x2e, 0x74, 0x77, 0x69, 0x72, 0x70, 0x2e, 0x64, 0x65,
	0x73, 0x61, 0x66, 0x69, 0x6f, 0x47, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x61, 0x12,
	0x44, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x45, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x61, 0x73, 0x12, 0x16,
	0x2e, 0x74, 0x77, 0x69, 0x72, 0x70, 0x2e, 0x64, 0x65, 0x73, 0x61, 0x66, 0x69, 0x6f, 0x47, 0x6f,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1d, 0x2e, 0x74, 0x77, 0x69, 0x72, 0x70, 0x2e, 0x64,
	0x65, 0x73, 0x61, 0x66, 0x69, 0x6f, 0x47, 0x6f, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x6d, 0x70,
	0x72, 0x65, 0x73, 0x61, 0x73, 0x12, 0x40, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x45, 0x6d, 0x70, 0x72,
	0x65, 0x73, 0x61, 0x12, 0x18, 0x2e, 0x74, 0x77, 0x69, 0x72, 0x70, 0x2e, 0x64, 0x65, 0x73, 0x61,
	0x66, 0x69, 0x6f, 0x47, 0x6f, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x49, 0x64, 0x1a, 0x18, 0x2e,
	0x74, 0x77, 0x69, 0x72, 0x70, 0x2e, 0x64, 0x65, 0x73, 0x61, 0x66, 0x69, 0x6f, 0x47, 0x6f, 0x2e,
	0x45, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x61, 0x12, 0x45, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x45, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x61, 0x42, 0x79, 0x49, 0x64, 0x12, 0x18, 0x2e, 0x74,
	0x77, 0x69, 0x72, 0x70, 0x2e, 0x64, 0x65, 0x73, 0x61, 0x66, 0x69, 0x6f, 0x47, 0x6f, 0x2e, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x49, 0x64, 0x1a, 0x16, 0x2e, 0x74, 0x77, 0x69, 0x72, 0x70, 0x2e, 0x64,
	0x65, 0x73, 0x61, 0x66, 0x69, 0x6f, 0x47, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x49,
	0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x61, 0x42,
	0x79, 0x4e, 0x6f, 0x6d, 0x65, 0x12, 0x1a, 0x2e, 0x74, 0x77, 0x69, 0x72, 0x70, 0x2e, 0x64, 0x65,
	0x73, 0x61, 0x66, 0x69, 0x6f, 0x47, 0x6f, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x4e, 0x6f, 0x6d,
	0x65, 0x1a, 0x16, 0x2e, 0x74, 0x77, 0x69, 0x72, 0x70, 0x2e, 0x64, 0x65, 0x73, 0x61, 0x66, 0x69,
	0x6f, 0x47, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x72,
	0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_empresa_proto_rawDescOnce sync.Once
	file_empresa_proto_rawDescData = file_empresa_proto_rawDesc
)

func file_empresa_proto_rawDescGZIP() []byte {
	file_empresa_proto_rawDescOnce.Do(func() {
		file_empresa_proto_rawDescData = protoimpl.X.CompressGZIP(file_empresa_proto_rawDescData)
	})
	return file_empresa_proto_rawDescData
}

var file_empresa_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_empresa_proto_goTypes = []interface{}{
	(*Empresa)(nil),             // 0: twirp.desafioGo.Empresa
	(*ListEmpresas)(nil),        // 1: twirp.desafioGo.ListEmpresas
	(*ParamId)(nil),             // 2: twirp.desafioGo.ParamId
	(*ParamNome)(nil),           // 3: twirp.desafioGo.ParamNome
	(*ParamEmissoes)(nil),       // 4: twirp.desafioGo.ParamEmissoes
	(*UpdateEmissoesParam)(nil), // 5: twirp.desafioGo.UpdateEmissoesParam
	(*Empty)(nil),               // 6: twirp.desafioGo.Empty
}
var file_empresa_proto_depIdxs = []int32{
	0, // 0: twirp.desafioGo.ListEmpresas.empresas:type_name -> twirp.desafioGo.Empresa
	0, // 1: twirp.desafioGo.EmpresaService.AddEmpresa:input_type -> twirp.desafioGo.Empresa
	5, // 2: twirp.desafioGo.EmpresaService.UpdateEmissoes:input_type -> twirp.desafioGo.UpdateEmissoesParam
	6, // 3: twirp.desafioGo.EmpresaService.GetEmpresas:input_type -> twirp.desafioGo.Empty
	2, // 4: twirp.desafioGo.EmpresaService.GetEmpresa:input_type -> twirp.desafioGo.ParamId
	2, // 5: twirp.desafioGo.EmpresaService.DeleteEmpresaById:input_type -> twirp.desafioGo.ParamId
	3, // 6: twirp.desafioGo.EmpresaService.DeleteEmpresaByNome:input_type -> twirp.desafioGo.ParamNome
	0, // 7: twirp.desafioGo.EmpresaService.AddEmpresa:output_type -> twirp.desafioGo.Empresa
	0, // 8: twirp.desafioGo.EmpresaService.UpdateEmissoes:output_type -> twirp.desafioGo.Empresa
	1, // 9: twirp.desafioGo.EmpresaService.GetEmpresas:output_type -> twirp.desafioGo.ListEmpresas
	0, // 10: twirp.desafioGo.EmpresaService.GetEmpresa:output_type -> twirp.desafioGo.Empresa
	6, // 11: twirp.desafioGo.EmpresaService.DeleteEmpresaById:output_type -> twirp.desafioGo.Empty
	6, // 12: twirp.desafioGo.EmpresaService.DeleteEmpresaByNome:output_type -> twirp.desafioGo.Empty
	7, // [7:13] is the sub-list for method output_type
	1, // [1:7] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_empresa_proto_init() }
func file_empresa_proto_init() {
	if File_empresa_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_empresa_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empresa); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_empresa_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListEmpresas); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_empresa_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParamId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_empresa_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParamNome); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_empresa_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParamEmissoes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_empresa_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateEmissoesParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_empresa_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_empresa_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_empresa_proto_goTypes,
		DependencyIndexes: file_empresa_proto_depIdxs,
		MessageInfos:      file_empresa_proto_msgTypes,
	}.Build()
	File_empresa_proto = out.File
	file_empresa_proto_rawDesc = nil
	file_empresa_proto_goTypes = nil
	file_empresa_proto_depIdxs = nil
}
